### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'nodes' with new Keras on word2vec example

### ISSUE THREAD

**Issue by joelkuiper** [niitsuma/word2vec-keras-in-gensim#2]
Hey, just encountered this issue, seems it's still calling some legacy code? 

```
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    sys.exit(main())
  File "train.py", line 179, in main
    train(args)
  File "train.py", line 140, in train
    trim_rule=None)
  File "/Users/joelkuiper/anaconda/lib/python2.7/site-packages/gensim-0.12.4-py2.7-macosx-10.5-x86_64.egg/gensim/models/word2vec.py", line 445, in __init__
    self.train(sentences)
  File "/Users/joelkuiper/Repositories/DeepOntology/word2veckeras.py", line 249, in train
    self.kerasmodel.nodes['embedding'].set_weights([self.syn0])
AttributeError: 'Graph' object has no attribute 'nodes'
```

Keras==1.0.0

**Comment by joelkuiper** [comment]
Changing it to use _.graph_nodes instead gives this error 

```
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    sys.exit(main())
  File "train.py", line 179, in main
    train(args)
  File "train.py", line 140, in train
    trim_rule=None)
  File "/Users/joelkuiper/anaconda/lib/python2.7/site-packages/gensim-0.12.4-py2.7-macosx-10.5-x86_64.egg/gensim/models/word2vec.py", line 445, in __init__
    self.train(sentences)
  File "/Users/joelkuiper/Repositories/DeepOntology/word2veckeras.py", line 250, in train
    self.kerasmodel.fit_generator(gen,samples_per_epoch=samples_per_epoch, nb_epoch=self.iter, verbose=0)
  File "/Users/joelkuiper/anaconda/lib/python2.7/site-packages/keras/legacy/models.py", line 644, in fit_generator
    class_weight=class_weight)
  File "/Users/joelkuiper/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 1337, in fit_generator
    raise e
Exception: Error when checking model input: expected index to have shape (None, 1) but got array with shape (128, 16)
```

Also had to change the input layer dtypes from int to "int" otherwise it would give a type error?

**Comment by niitsuma** [comment]
I found resent keras update remove Graph interface.
To fix this problem, I wrote to setup.py 

``` python
setup(name='word2veckeras',
...
install_requires=[... ,'keras<=0.3.1']
```

**Comment by joelkuiper** [comment]
Downgrading is not an option. I guess I'll rewrite using the current stable API once I have time.
