### ISSUE TITLE
Example returns error

### ISSUE THREAD

**Issue by ammsa** [niitsuma/word2vec-keras-in-gensim#3]
I've tried the following exmaple shown in the repo's page:

```
from nltk.corpus import brown
brk = Word2VecKeras(brown.sents(),iter=10)
print( brk.most_similar('the', topn=5))
```

but I got the following error:

```

>>> from nltk.corpus import brown
>>> brk = Word2VecKeras(brown.sents(),iter=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mustafa/.virtualenvs/ML/lib/python2.7/site-packages/gensim/models/word2vec.py", line 445, in __init__
    self.train(sentences)
  File "/Users/mustafa/.virtualenvs/ML/lib/python2.7/site-packages/word2veckeras/word2veckeras.py", line 372, in train
    model=self,cbow_mean=self.cbow_mean
  File "/Users/mustafa/.virtualenvs/ML/lib/python2.7/site-packages/word2veckeras/word2veckeras.py", line 194, in build_keras_model_cbow
    kerasmodel.add_node(Activation('sigmoid'), name='sigmoid',inputs=['average','embedpoint'], merge_mode='dot',dot_axes=-1)
  File "keras/legacy/models.py", line 183, in add_node
    name='merge_inputs_for_' + name)
  File "keras/engine/topology.py", line 1119, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "keras/engine/topology.py", line 155, in create_node
    output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes))
  File "keras/engine/topology.py", line 1310, in get_output_shape_for
    axes=dot_axes)
  File "/Users/mustafa/.virtualenvs/ML/lib/python2.7/site-packages/numpy/core/numeric.py", line 1302, in tensordot
    if as_[axes_a[k]] != bs[axes_b[k]]:
IndexError: tuple index out of range
```

**Comment by SimonPavlik** [comment]
Got the same error with Keras 1.0.6 caused by a bug in the Merge layer. The issue was fixed by a recent [commit](https://github.com/fchollet/keras/commit/cfbaec60c77448e6249f912d4b4d4a8c079f2bcf) to Keras.

You can get the update by installing directly from the master branch:
`pip install git+git://github.com/fchollet/keras.git --upgrade`

Running `Word2VecKeras` with the required version of Keras==0.3.1 will also help.

**Comment by alaabd** [comment]
I have the sme error, i try to to install keras from this link and it didn't work??? can you help

 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 630, in convolution
    input_channels_dim = input.get_shape()[num_spatial_dims + 1]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 502, in __getitem__
    return self._dims[key]
IndexError: list index out of range
